name: $name
version: $version
main: de.leghast.showcase.Showcase
api-version: "$apiVersion"
authors: [GhastCraftHD]
description: $description

commands:
  showcase:
    description: The main command for Showcase
    permission: showcase.use

permissions:
  showcase.use:
    default: op
    description: The permission that lets you use Showcase
