name: $name
version: $version
main: de.leghast.showcase.Showcase
api-version: "$apiVersion"
authors: [GhastCraftHD]
description: $description

permissions:
  showcase.use:
    default: op
    description: The permission that lets you use Showcase
